// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: twitchgame.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwitchGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BoxArtUrl   string `protobuf:"bytes,3,opt,name=box_art_url,json=boxArtUrl,proto3" json:"box_art_url,omitempty"`
	ViewerCount int32  `protobuf:"varint,4,opt,name=viewer_count,json=viewerCount,proto3" json:"viewer_count,omitempty"`
	Popularity  int32  `protobuf:"varint,5,opt,name=popularity,proto3" json:"popularity,omitempty"`
}

func (x *TwitchGame) Reset() {
	*x = TwitchGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchgame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitchGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitchGame) ProtoMessage() {}

func (x *TwitchGame) ProtoReflect() protoreflect.Message {
	mi := &file_twitchgame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitchGame.ProtoReflect.Descriptor instead.
func (*TwitchGame) Descriptor() ([]byte, []int) {
	return file_twitchgame_proto_rawDescGZIP(), []int{0}
}

func (x *TwitchGame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TwitchGame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TwitchGame) GetBoxArtUrl() string {
	if x != nil {
		return x.BoxArtUrl
	}
	return ""
}

func (x *TwitchGame) GetViewerCount() int32 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

func (x *TwitchGame) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

var File_twitchgame_proto protoreflect.FileDescriptor

var file_twitchgame_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x54,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0b, 0x62, 0x6f, 0x78, 0x5f, 0x61, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x78, 0x41, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a,
	0x0c, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x69, 0x63, 0x68, 0x61, 0x65, 0x6c, 0x66, 0x69, 0x6f, 0x72, 0x65, 0x74, 0x74, 0x69, 0x2f, 0x74,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_twitchgame_proto_rawDescOnce sync.Once
	file_twitchgame_proto_rawDescData = file_twitchgame_proto_rawDesc
)

func file_twitchgame_proto_rawDescGZIP() []byte {
	file_twitchgame_proto_rawDescOnce.Do(func() {
		file_twitchgame_proto_rawDescData = protoimpl.X.CompressGZIP(file_twitchgame_proto_rawDescData)
	})
	return file_twitchgame_proto_rawDescData
}

var file_twitchgame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_twitchgame_proto_goTypes = []interface{}{
	(*TwitchGame)(nil), // 0: models.TwitchGame
}
var file_twitchgame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_twitchgame_proto_init() }
func file_twitchgame_proto_init() {
	if File_twitchgame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_twitchgame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitchGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_twitchgame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_twitchgame_proto_goTypes,
		DependencyIndexes: file_twitchgame_proto_depIdxs,
		MessageInfos:      file_twitchgame_proto_msgTypes,
	}.Build()
	File_twitchgame_proto = out.File
	file_twitchgame_proto_rawDesc = nil
	file_twitchgame_proto_goTypes = nil
	file_twitchgame_proto_depIdxs = nil
}
