name: twitch-chat-stats-producer
region: sfo
workers:
  - image:
      registry: docker.io
      repository: michaelfioretti/twitch-chat-stats
      registry_type: DOCKER_HUB
      registry_credentials: ${DOCKER_USERNAME}:${DOCKER_PASSWORD}
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    name: michaelfioretti-twitch-chat-stat
envs:
  - key: TWITCH_CLIENT_ID
    value: ${TWITCH_CLIENT_ID}
  - key: TWITCH_CLIENT_SECRET
    value: ${TWITCH_CLIENT_SECRET}
  - key: DB_USERNAME
    value: ${DB_USERNAME}
  - key: DB_PASSWORD
    value: ${DB_PASSWORD}
  - key: TWITCH_CHAT_API_HEARTBEAT_URL
    value: ${TWITCH_CHAT_API_HEARTBEAT_URL}
features:
  - buildpack-stack=ubuntu-22
ingress: {}
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
