apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9094
    targetPort: 9094
    nodePort: 30094
  selector:
    app: kafka
