apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: kafka-deployment
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/kafka
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: kafka-deployment
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka-deployment
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: chmod-data-directory
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/lib/kafka/data && rm -rf /var/lib/kafka/data/lost+found"]
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        env:
        - name: KAFKA_CFG_LISTENERS
          value: "INTERNAL://:9092,CONTROLLER://:9093,SASL_PLAINTEXT://:9094"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "INTERNAL://localhost:9092,SASL_PLAINTEXT://134.209.0.242:30094"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
        - name: KAFKA_CFG_SASL_ENABLED_MECHANISMS
          value: "PLAIN"
        - name: KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL
          value: "PLAIN"
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka:9093"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "kafka-deployment-id"
        - name: KAFKA_CFG_LOG_DIRS
          value: "/var/lib/kafka/data"
        ports:
        - containerPort: 9094
          name: kafka
        - containerPort: 9093
          name: controller
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-deployment
spec:
  type: NodePort
  ports:
  - port: 9094
    targetPort: 9094
    nodePort: 30094
  selector:
    app: kafka
