apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /mnt/data && chown -R 1001:1001 /mnt/data && rm -rf /mnt/data/lost+found"]
        volumeMounts:
        - name: kafka-data
          mountPath: /mnt/data
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        - containerPort: 9094
        env:
        # Load JAAS
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"
        # Basic info
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_LOG_DIRS
          value: "/mnt/data"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "twitch-chat-stats-cluster-id"
        - name: KAFKA_ENABLE_KRAFT
          value: "true"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        # Internal/external listeners
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,SASL_PLAINTEXT://0.0.0.0:9094"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092,SASL_PLAINTEXT://165.227.109.90:9094"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka:9093"
        # Security definitions and authentication
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
        - name: KAFKA_SECURITY_INTER_BROKER_PROTOCOL
          value: "PLAINTEXT"
        - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
          value: "PLAIN"
        - name: KAFKA_SASL_ENABLED_MECHANISMS
          value: "PLAIN"
        volumeMounts:
        - name: kafka-data
          mountPath: /mnt/data
        - name: jaas-config
          mountPath: /etc/kafka/jaas.conf
          subPath: jaas.conf
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-pvc
      - name: jaas-config
        secret:
          secretName: kafka-jaas-config
