apiVersion: v1
kind: Service
metadata:
  name: kafka-clusterip
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - name: controller
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: internal
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: kafka
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - name: external
    port: 9094
    targetPort: 9094
    nodePort: 30094
    protocol: TCP
  selector:
    app: kafka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/lib/kafka/data && chown -R 1001:1001 /var/lib/kafka/data && rm -rf /var/lib/kafka/data/lost+found"]
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        - containerPort: 9093
        - containerPort: 30094
        env:
        # Basic info
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "twitch-chat-stats-cluster-id"
        - name: KAFKA_ENABLE_KRAFT
          value: "true"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        # Listeners
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
        - name: KAFKA_LISTENERS
          value: CONTROLLER://:9092,INTERNAL://:9093,EXTERNAL://:9094
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://:9093,EXTERNAL://134.209.0.242:9094
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 1@:9092
          # SASL
        - name: KAFKA_AUTHORIZER_CLASS_NAME
          value: org.apache.kafka.metadata.authorizer.StandardAuthorizer
        - name: KAFKA_SASL_ENABLED_MECHANISMS
          value: 'PLAIN'
        - name: KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL
          value: 'PLAIN'
        - name: KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL
          value: 'PLAIN'
        - name: KAFKA_CFG_SECURITY_PROTOCOL
          value: 'SASL_PLAINTEXT'
        - name: KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL
          value: "PLAIN"
          # Set the KAFKA_OPTS environment variable
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/secrets/jaas.conf"
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
        - name: kafka-jaas-config
          mountPath: /etc/kafka/secrets
          readOnly: true
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc
      - name: kafka-jaas-config
        secret:
          secretName: kafka-jaas-config
