---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgATkv2gORhYMvj4gmdKNs+ZcSj20DEJf57JeFlLFOhvNA/na42lYMZq8aQ6np5yVKOWZQUzNpU9Q47G3lmD5YXpi7wvGqQI1pzKhQn76sxfz3stZRm2ynkSv753kBixPqcqDxIaPAu5ILxUiH7NO+VujlEEfKCng86FRTGSf7R3UmtueHXmSgOgGBBGpG36JIu+ICKHApcxD9CGR1QySaPSSrqUeuEbHb0owEQOpXVh2glkrLMeeCBeqAtj9q7GTblcWW93aXgJgN2KvcOfTWkZCMctXAJPeQWHakh9qJisv4pRioCZqsPIit622MxUrljd5iTd2GEwxvmqK//DGQz1MG3fjXIoSr3QL6B0IuVZAFjpXOeeAQtrkrBtpcS8BP0UyTShGwhEq9YF6M9nTbCNup+sOO/pNSRWP56AgbXhGHQ3PZZ/AfDNo58MBWwcgKNC2elwVBRW4To9PWCxmOg24yhYUIs5VBKA7P3aamWVMYURB0EGN5C+AcL+xTmhe/aMGbm/02fIhvJS5NPApYvdgsIAb62ruP2Cc9xeQ03orpu8eN71xKvsJ56DptVAPop3w8wldC1ymG0MV92qj+CptS91d/6wSfjKw4+6byLiWA9blJAjkqqNth1XPe9U9o/XTtnxZm43Ts+wYLdtKllD8fvPF2PINTXXp0wC+wsg9JDeYx9jb9As6+4yhgzg0CCDBk/ssjMApsFdCmbCNgc6w8tFtDljShNhHrJYkN03UaB29sDsnQW75SK6jAXf6z0erLP+X7v+1lBxvLn7poAHgUitebS2kLYR0Maq2PtLA7I0YPiNO1oelPqqou+pLxd1xfW3/fn5jVjb6nC8iX3ngIFbDrWkBYgzrxSmcyiCNzeQdLpEneu/nqVWBBjlLgCcUC3vab/lMLdd7fCERKvyz/Z4hWpLSZp1JE+Ua5T218v4R4NJTQOO2lfTVQo03PHC
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
