name: CI/CD

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the project
      run: make build

    - name: Generate coverage report
      run: make coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: michaelfioretti
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: michaelfioretti/twitch-chat-stats:latest

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Authenticate with DigitalOcean
      run: doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Trigger DO App Platform redeploy
      run: doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yaml

    - name: Log out from Docker Hub
      run: docker logout
